version: '3'
services:
  db:
    image: mongo:latest
    restart: always
    container_name: db
    ports:
      - '27017:27017'
    networks:
      - via-sacra-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  backend:
    build: .
    restart: always
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - via-sacra-network

networks:
  via-sacra-network:
    driver: bridge
